# KEEPING IT FOR DEMO PURPOSE, IN CASE WE NEED A FULLY ISOLATED DATABASE ENV
version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/src:/app/src
    ports:
      - '4000:4000'
    env_file:
      - ./app/.env
  mariadb:
    image: mariadb:10.4
    restart: on-failure
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/init.sql:/data/app/init.sql
    env_file:
      - ./mariadb/.env
    command: 'mysqld --init-file /data/app/init.sql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 4001:80
    env_file:
      - ./.env
    depends_on:
      - mariadb
