# NOT REALLY NEEDED, BUT MAY BE USEFUL LATER ON
# you can run `npm run start:dev` directly inside app
version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/src:/app/src
    ports:
      - '4000:4000'
    env_file:
      - ./app/.env
