FROM node:12-alpine

WORKDIR /app

# Copy package.json for caching node_modules
COPY package.json /app/package.json

# Copy lockfile for packages consistency
COPY package-lock.json /app/

# Install packages
RUN npm install

# Copy source files
COPY . .

EXPOSE $API_PORT

ENTRYPOINT ["npm", "run", "start:dev"]
